server:
    port: 8081

spring:
    #配置数据库连接
    datasource:
        url: jdbc:mysql://localhost:3306/db_upms?useSSL=false&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
#    profiles:
#        active: dev
    #配置redis数据库连接
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 3600 # 连接超时时间（毫秒）
        jedis:
            pool:
                max-idle: 20      # 连接池中的最大空闲连接
                min-idle: 1
                max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
                max-wait: 60000   #连接池最大阻塞等待时间
        database: 0   #默认是索引为的0的数据库


jwt:
    Header: Authorization #JWT存储的请求头
    secret: mybatisPlus123 #JWT加解密使用的密钥
    expiration: 7200 #JWT的超期限时间(60*60*2)
    tokenHead: Bearer  #JWT负载中拿到开头
    refreshTokenExpire: 604800

swagger:
    enable: false