server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_upms?useSSL=false&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
    mapper-locations: classpath:/mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.demo.mybatisplus.model
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 3
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 2
        #驼峰下划线转换
        db-column-underline: true
    configuration:
        #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
        map-underscore-to-camel-case: true
        cache-enabled: false
        #配置JdbcTypeForNull, oracle数据库必须配置
        jdbc-type-for-null: 'null'
        #
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
    level:
        root: info #日志配置DEBUG,INFO,WARN,ERROR
        com.demo.mybatisplus.mapper: debug
    file: log/catalian.log #配置日志生成路径